apiVersion: v1
kind: Service
metadata:
  name: genai-service
spec:
  type: LoadBalancer  # Exposes the service externally
  selector:
    app: genai-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000